### ISSUE TITLE
別タブで放置するとオブジェクトが重なってしまう

### ISSUE THREAD

**Issue by M-Onitsuka** [ban-masa/ban-masa.github.io#1]
CTBを起動した状態でブラウザのタブを移動すると落下するオブジェクト(C◯K)が重なってしまいます

**Comment by ShogoMakino** [comment]
直し方はわかりませんが、別タブで放置すると物理エンジンのほうは動かないけどIntervalの関数は呼ばれていて、stateが切り替わってしまうのが原因のようですね。

**Comment by ShogoMakino** [comment]
と思ったら #2 で表示範囲を変えたことにより画像が重なることはなくなったようですね(ただし積み重なった状態で落ちてくる)

**Comment by ban-masa** [comment]
後ほど、タブのフォーカスを見て動作を切り替える機能を追加しようと考えています。
（CTBを起動したままタブ移動する状況があまり想像できないですけれども）

**Comment by ban-masa** [comment]
タブ移動後には処理を止めるよう実装し、動作確認をしました。
が、コーディングが汚いのでどこかにバグがあるかもしれません。
