### ISSUE TITLE
Drop前にタワーと干渉する

### ISSUE THREAD

**Issue by ShogoMakino** [ban-masa/ban-masa.github.io#2]
タワーが高くなってきたときに、タワーとこれから落とすちょうは◯きが重なってしまいます。
この状態だと、Dropする前のちょうは◯きを回転、もしくは移動させたとき、既に立っているタワーと干渉してしまうようです。
できるのかわかりませんが、Dropする前は別のレイヤーにしておく、タワーが高くなったら画面全体をスライドさせる等の処理を加えるのはいかがでしょうか。

![ctb_crop0](https://user-images.githubusercontent.com/14898824/34152323-8be9b25e-e4f1-11e7-9288-5df30aa4a3de.png)
1枚目：高くなったタワー

![ctb_crop1](https://user-images.githubusercontent.com/14898824/34152324-8c131d06-e4f1-11e7-9918-3ae7c4ebcfa9.png)
2枚目：次のちょうは◯きが出てきたところ。既にあるタワーと重なっています。

![ctb_crop2](https://user-images.githubusercontent.com/14898824/34152325-8c397d2a-e4f1-11e7-9dd3-c3fa501d1377.png)
3枚目：回転させた様子。わかりにくいですが、タワーの一番上のちょうは◯きと背景の餃子の位置を比べると、少し動いているのが分かると思います。

![ctb_crop3](https://user-images.githubusercontent.com/14898824/34152326-8c5e09f6-e4f1-11e7-8c7f-c9367c7f180c.png)
4枚目：右に移動させた様子。タワー全体が右にスライドしています。

干渉しない位置にタワーを立てるのも戦略のうちであり、このように積むのは悪い積み方とお考えであればこのままでもいいかもしれませんが、ご検討いただけると幸いです。

**Comment by ban-masa** [comment]
対応してみました。(4b1726c9ec8b48bab52e5ac2dec1766c4cf93c61)
本家とは異なり、全体が画面に収まるよう縮尺が変化し、初期生成位置が上方へと移動していきます。
自分ではデバッグできるほど積み上げることができませんでしたので、よろしければ検証お願いします。
（最低限の動作確認はした）

**Comment by ShogoMakino** [comment]
ありがとうございます。だいぶ積めるようになったのでいいとおもいます。
